[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/chitalnyizal"
  to = "/.netlify/functions/library-proxy?action=proxy&page=chitalnyizal"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/register-user"
  [headers.values]
    Access-Control-Allow-Origin = "https://pro-culinaria.ru"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
